name: 'dependency-review'
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Dependency Vulnerability Check'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: 'high'
          comment-summary-in-pr: 'always'
          license-check: 'false'
          show-openssf-scorecard: 'false'